message: '&cUnknown command!'

# List any commands here that cause conflicts
exempt-commands:
  - "exemptcommand1"
  - "exemptcommand2"
  - "exemptcommand3"

# SINGLE HEX & GRADIENT EXAMPLES
#'&#FFD700&lUnknown command!'
#'&l&gradient:#FFD700:#FFA500:#FF8C00:#FF6347&Unknown command!'
